#!/bin/bash
# Initialize an Obsidian vault for a research paper project
# Usage: bash init_vault.sh "project-name" "/output/path"

set -euo pipefail

PROJECT_NAME="${1:?Usage: init_vault.sh <project-name> <output-path>}"
OUTPUT_PATH="${2:?Usage: init_vault.sh <project-name> <output-path>}"

VAULT_ROOT="${OUTPUT_PATH}/${PROJECT_NAME}"

if [ -d "$VAULT_ROOT" ]; then
    echo "Warning: Vault already exists at ${VAULT_ROOT}. Skipping initialization."
    exit 0
fi

echo "Creating vault: ${VAULT_ROOT}"

# Create directory structure
mkdir -p "${VAULT_ROOT}/00 - Home"
mkdir -p "${VAULT_ROOT}/01 - Paper Structure"
mkdir -p "${VAULT_ROOT}/02 - Literature"
mkdir -p "${VAULT_ROOT}/02 - Literature/paper-notes"
mkdir -p "${VAULT_ROOT}/03 - Experiments"
mkdir -p "${VAULT_ROOT}/04 - Concepts"
mkdir -p "${VAULT_ROOT}/05 - Figures"
mkdir -p "${VAULT_ROOT}/06 - Writing Guide"
mkdir -p "${VAULT_ROOT}/07 - Action Items"

# Home
cat > "${VAULT_ROOT}/00 - Home/Home.md" << 'HOMEEOF'
# Project Home

## Contribution Statement
<!-- Fill in from Phase 1: Ideation -->

## Narrative Arc
<!-- Problem → Gap → Insight → Approach → Evidence -->

## Quick Links
- [[Section Outline]] — paper structure and writing briefs
- [[Positioning Matrix]] — related work landscape
- [[Gap Analysis]] — what existing work misses
- [[Experiment Plan]] — evaluation design
- [[Figure Index]] — all diagrams and charts
- [[Master Checklist]] — what's done, what's pending

## Project Metadata
- **Target Venue:**
- **Page Limit:**
- **Submission Deadline:**
- **Domain:**
HOMEEOF

# Paper Structure
cat > "${VAULT_ROOT}/01 - Paper Structure/Section Outline.md" << 'EOF'
# Section Outline

## Paper Structure
<!-- Generated by Phase 3 -->

| Section | Pages | Status |
|---------|-------|--------|
| Introduction | 1.5-2 | |
| Background | 1-1.5 | |
| Design | 3-4 | |
| Implementation | 0.5-1 | |
| Evaluation | 3-4 | |
| Discussion | 0.5-1 | |
| Related Work | 1.5-2 | |
| Conclusion | 0.5 | |

## Per-Section Briefs
<!-- One subsection per section with purpose, key points, and pitfalls -->
EOF

cat > "${VAULT_ROOT}/01 - Paper Structure/Argument Flow.md" << 'EOF'
# Argument Flow

How each section connects to the next. The paper tells one continuous story.

## Flow
1. **Introduction** establishes the problem and claims → motivates...
2. **Background** gives the reader enough context to understand the approach → enables...
3. **Design** presents the technical contribution → implemented as...
4. **Implementation** describes engineering decisions → evaluated by...
5. **Evaluation** provides evidence for the claims → compared against...
6. **Related Work** positions the contribution in the landscape → concluded by...
7. **Conclusion** restates contributions and future work

## Key Transitions
<!-- Note the logical bridge between each pair of sections -->
EOF

# Literature
cat > "${VAULT_ROOT}/02 - Literature/Positioning Matrix.md" << 'EOF'
# Positioning Matrix

| Paper | Year | Venue | Key Technique | Limitation (our advantage) |
|-------|------|-------|---------------|---------------------------|
| | | | | |

## Search Queries Used
<!-- Record all search queries for reproducibility -->
EOF

cat > "${VAULT_ROOT}/02 - Literature/Gap Analysis.md" << 'EOF'
# Gap Analysis

## What Existing Work Does Well
<!-- Fair characterization of prior art -->

## What's Missing
<!-- The specific gap your paper fills -->

## How Our Work Fills the Gap
<!-- Direct connection to contribution statement -->
EOF

# Experiments
cat > "${VAULT_ROOT}/03 - Experiments/Experiment Plan.md" << 'EOF'
# Experiment Plan

## Claim-Experiment Matrix

| Claim | RQ | Experiment Type | Baselines | Metrics | Dataset | Estimated Time |
|-------|----|----|-----------|---------|---------|----------------|
| | | | | | | |

## Threats to Validity
### Internal
### External
### Construct
EOF

cat > "${VAULT_ROOT}/03 - Experiments/Baselines.md" << 'EOF'
# Baselines

## State-of-the-Art Systems

| System | Paper | Venue | Year | Code Available? | Dataset Used | Key Metrics Reported |
|--------|-------|-------|------|-----------------|-------------|---------------------|
| | | | | | | |

## Reproduction Notes
<!-- Notes on reproducing baseline results -->
EOF

# Figures
cat > "${VAULT_ROOT}/05 - Figures/Figure Index.md" << 'EOF'
# Figure Index

| Fig # | Caption | Type | Section | Status | Source File |
|-------|---------|------|---------|--------|-------------|
| | | | | | |
EOF

# Writing Guide
cat > "${VAULT_ROOT}/06 - Writing Guide/Voice DNA.md" << 'EOF'
# Voice DNA

See [[Banned Phrases]] for the kill list.

## Core Rules
1. Write technically and academically
2. Get to the point. No throat-clearing
3. Be specific: numbers, names, concrete details
4. Vary sentence length
5. Use physical verbs: "stripped back" not "simplified"
6. Parenthetical asides for editorial commentary
7. Never pad output

## Formatting
- Numbers as digits with commas
- NO em dashes. Use commas, periods, colons, semicolons, or parentheses
- Bold sparingly
EOF

cat > "${VAULT_ROOT}/06 - Writing Guide/Banned Phrases.md" << 'EOF'
# Banned Phrases

If any of these appear in output, the output fails. No exceptions.

## Dead AI Language
- "In today's [anything]..."
- "It's important/worth noting..."
- "Delve" / "Dive into" / "Unpack"
- "Harness" / "Leverage" / "Utilize"
- "Landscape" / "Realm" / "Robust"
- "Game-changer" / "Cutting-edge"
- "Straightforward"
- "In order to"

## Dead Transitions
- "Moving forward" / "At the end of the day"
- "To put this in perspective..."
- "What makes this particularly interesting is..."
- "In other words..."

## FATAL Pattern
- "This isn't X. This is Y." and ALL variations
- "Not X. Y." / "Forget X. This is Y." / "Less X, more Y."
- Any sentence that negates one framing then asserts a corrected one
EOF

cat > "${VAULT_ROOT}/06 - Writing Guide/Writing Samples.md" << 'EOF'
# Writing Samples

Calibration examples. Add your own as the paper develops.

## Good Patterns
<!-- Paste excerpts from your drafts that hit the right voice -->

## Anti-Patterns
<!-- Paste and annotate examples of what NOT to write -->
EOF

# Action Items
cat > "${VAULT_ROOT}/07 - Action Items/Master Checklist.md" << 'EOF'
# Master Checklist

## Phase 1: Ideation
- [ ] Core idea articulated
- [ ] Contribution statement drafted
- [ ] Narrative arc defined
- [ ] Novelty stress-tested against literature

## Phase 2: Literature Review
- [ ] Search queries executed
- [ ] Positioning matrix complete
- [ ] Gap analysis written
- [ ] Related work section drafted

## Phase 3: Paper Structure
- [ ] Section outline with page budgets
- [ ] Per-section writing briefs
- [ ] LaTeX skeleton generated
- [ ] Argument flow mapped

## Phase 4: Experiment Design
- [ ] Claim-experiment matrix built
- [ ] Baselines identified and availability checked
- [ ] Metrics defined
- [ ] Threats to validity identified
- [ ] Evaluation tables/figures designed

## Phase 5: Diagrams
- [ ] System architecture figure
- [ ] Evaluation figures (charts, tables)
- [ ] All figures captioned and referenced

## Phase 6: Writing
- [ ] Introduction drafted
- [ ] Background drafted
- [ ] Design/approach drafted
- [ ] Implementation drafted
- [ ] Evaluation drafted
- [ ] Related work drafted
- [ ] Conclusion drafted
- [ ] Voice DNA self-check passed on all sections

## Phase 7: Polish
- [ ] Cross-references verified
- [ ] Bibliography complete and venue-validated
- [ ] Page count within limits
- [ ] Anonymization (if required)
- [ ] Final proofread
EOF

cat > "${VAULT_ROOT}/07 - Action Items/Timeline.md" << 'EOF'
# Timeline

| Milestone | Target Date | Status |
|-----------|------------|--------|
| Idea finalized | | |
| Literature review complete | | |
| Paper structured | | |
| Experiments designed | | |
| First full draft | | |
| Internal review | | |
| Camera-ready | | |
| Submission | | |
EOF

echo "Vault created at: ${VAULT_ROOT}"
echo "Open in Obsidian: File > Open Vault > ${VAULT_ROOT}"
